title: Gamaliel Gutierrez
email: eglenelid.gamaliel@gmail.com
description: eglenelid-gamaliel.github.io is a personal website of Gamaliel Gutierrez.
baseurl: ""
url: ""

theme: minima

# Minima settings
github_username:  eglenelid-gamaliel
linkedin_username: eglenelid-gamaliel
twitter_username: theblueandroid

plugins:
  - jekyll-feed
