title: Gamaliel Gutierrez
email: eglenelid.gamaliel@gmail.com
description: Personal Portfolio
baseurl: ""
url: ""

theme: minima

# Minima settings
show_excerpts: true

github_username:  eglenelid-gamaliel
linkedin_username: eglenelid-gamaliel-gutierrez-hernández
twitter_username: theblueandroid

plugins:
  - jekyll-feed
